# Generated by Django 5.1.6 on 2025-02-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='emp_Id',
            new_name='emp_id',
        ),
    ]
