# Generated by Django 5.1.6 on 2025-02-20 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_student_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
    ]
